import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "NextMart | 10 munites delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-r from-yellow-200 to-white">
        {children}
      </body>
    </html>
  );
}
