import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/Provider";
import StoreProvider from "@/redux/StoreProvider";


export const metadata: Metadata = {
  title: "NextMart | 10 munites delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-[200vh] bg-linear-to-r from-yellow-200 to-white">
        <Provider>
          <StoreProvider>
          {children}
          </StoreProvider>
        </Provider>
      </body>
    </html>
  );
}
